# API Tests

All Grocery Items Test
---------------------------------
* TÜM GROCERY LİSTESİ ÇEKİLDİ VE STATUS KODU DOĞRULANDI
* GROCERY LİSTESİNDEKİ DATA BOYUTUNUN "2" OLDUĞU DOĞRULANDI
* GROCERY LİSTESİNDEKİ TÜM PARAMETRELERİN GELDİĞİ DOĞRULANDI

First Grocery Item Test
--------------------------
* BİRİNCİ GROCERY LİSTESİ ÇEKİLDİ VE STATUS KODU DOĞRULANDI
* BİRİNCİ GROCERY LİSTESİNDEKİ TÜM PARAMETRELERİN GELDİĞİ DOĞRULANDI
* BİRİNCİ GROCERY LİSTESİNDEKİ TÜM PARAMETRELERİN DEĞERLERİ DOĞRULANDI

Second Grocery Item Test
---------------------------
* İKİNCİ GROCERY LİSTESİ ÇEKİLDİ VE STATUS KODU DOĞRULANDI
* İKİNCİ GROCERY LİSTESİNDEKİ TÜM PARAMETRELERİN GELDİĞİ DOĞRULANDI
* İKİNCİ GROCERY LİSTESİNDEKİ TÜM PARAMETRELERİN DEĞERLERİ DOĞRULANDI

Negative Grocery Item Test
------------------------------
* HATALI GROCERY LİSTESİ ÇEKİLDİ VE STATUS KODU KONTROL EDİLDİ
* HATALI GROCERY LİSTESİ RESPONSESİNDEKİ TÜM PARAMETRELERİN DEĞERLERİ DOĞRULANDI


Add Grocery Item Successfully
---------------------------------

* GROCERY İÇİN YENİ PRODUCT EKLENDİ VE STATUS KODU KONTROL EDİLDİ
* EKLENEN ÜRÜN RESPONSESİNDEKİ PARAMETRELERİN DEĞERLERİ KONTROL EDİLDİ

Post Method With Missing Parameter
----------------------------------
* "id" PARAMETRESİ EKSİK ÜRÜN EKLENMEYE ÇALIŞILDI VE STATUS KODU KONTROL EDİLDİ
* ID PARAMETRESİ EKSİK RESPONSENİN TÜM PARAMETRE DEĞERLERİ KONTROL EDİLDİ
* "name" PARAMETRESİ EKSİK ÜRÜN EKLENMEYE ÇALIŞILDI VE STATUS KODU KONTROL EDİLDİ
* NAME PARAMETRESİ EKSİK RESPONSENİN TÜM PARAMETRE DEĞERLERİ KONTROL EDİLDİ
* "price" PARAMETRESİ EKSİK ÜRÜN EKLENMEYE ÇALIŞILDI VE STATUS KODU KONTROL EDİLDİ
* PRICE PARAMETRESİ EKSİK RESPONSENİN TÜM PARAMETRE DEĞERLERİ KONTROL EDİLDİ
* "stock" PARAMETRESİ EKSİK ÜRÜN EKLENMEYE ÇALIŞILDI VE STATUS KODU KONTROL EDİLDİ
* STOCK PARAMETRESİ EKSİK RESPONSENİN TÜM PARAMETRE DEĞERLERİ KONTROL EDİLDİ
